name = "grad_meh"
prefix = "grad_meh"
author = "Gruppe Adler"
folder_optionals = false
files = [
    "mod.cpp",
    "logo_active_ca.paa",
    "logo_ca.paa",
    "overview_co.paa",
    "logo_small_ca.paa",
    "LICENSE",
    "README.md"
]
key_name = "{{prefix}}-{{version}}"
authority = "{{version}}"

releasebuild = [
  "!copyInterceptPlugin"
]

[scripts.copyInterceptPlugin]
steps_windows = [
    'xcopy build\lib64\*.dll releases\\{{version}}\@{{prefix}}\intercept\ /Y /F'
]

show_output = true
