name = "Gruppe Adler MEH";
author = "DerZade, Willard";
logo = "logo_ca.paa";
logoOver = "logo_active_ca.paa";
tooltip = "Gruppe Adler MEH";
tooltipOwned = "Gruppe Adler MEH";
picture = "overview_co.paa";
actionName = "GitHub";
action = "https://github.com/gruppe-adler/grad_meh";
overview = "<br/><t align='center' size='0.75'>Visit Gruppe Adler on <t href='https://gruppe-adler.de/'>our Website</t> | <t href='http://discord.gruppe-adler.de'>Discord</t> | <t href='https://www.youtube.com/user/gruppeadler'>YouTube</t> | <t href='https://twitter.com/Gruppe_Adler'>Twitter</t></t><br/><br/>Gruppe Adler MEH is an Arma 3 modification built on intercept, which allows exporting Arma 3 maps.<br/>The aim of this project is not to generate finished map tiles for a WMTS, but to export all data that might be needed to generate such tiles or basically anything else.<br/>What you do with that data is up to you.";
hideName = 0;
hidePicture = 0;
dlcColor[] = {0.8196, 0.5529, 0.1216, 1};
logoSmall = "logo_small_ca.paa";