#ifndef GRAD_MEH_STATUS_CODES_H
#define GRAD_MEH_STATUS_CODES_H

#define GRAD_MEH_STATUS_OK 0
#define GRAD_MEH_STATUS_ERR_ARGS 1
#define GRAD_MEH_STATUS_ERR_ALREADY_RUNNING 2
#define GRAD_MEH_STATUS_ERR_NOT_FOUND 3
#define GRAD_MEH_STATUS_ERR_NO_WORLD_SIZE 4
#define GRAD_MEH_STATUS_ERR_PBO_NOT_FOUND 5
#define GRAD_MEH_STATUS_ERR_PBO_POPULATING 6

#endif /* GRAD_MEH_STATUS_CODES_H */
